spring:
  application:
    name: loan-service

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: ${SERVER_PORT:8080}

credit-analysis:
  url: ${CREDIT_ANALYSIS_URL:http://localhost:8081}

logging:
  level:
    com.projeto_final: DEBUG
